/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_1_argument {
	double arg1;
	double arg2;
};
typedef struct add_1_argument add_1_argument;

struct sub_1_argument {
	double arg1;
	double arg2;
};
typedef struct sub_1_argument sub_1_argument;

struct mul_1_argument {
	double arg1;
	double arg2;
};
typedef struct mul_1_argument mul_1_argument;

struct div_1_argument {
	double arg1;
	double arg2;
};
typedef struct div_1_argument div_1_argument;

#define CALCULATORPROG 0x20000001
#define CALCULATORVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  double * add_1(double , double , CLIENT *);
extern  double * add_1_svc(double , double , struct svc_req *);
#define SUB 2
extern  double * sub_1(double , double , CLIENT *);
extern  double * sub_1_svc(double , double , struct svc_req *);
#define MUL 3
extern  double * mul_1(double , double , CLIENT *);
extern  double * mul_1_svc(double , double , struct svc_req *);
#define DIV 4
extern  double * div_1(double , double , CLIENT *);
extern  double * div_1_svc(double , double , struct svc_req *);
extern int calculatorprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  double * add_1();
extern  double * add_1_svc();
#define SUB 2
extern  double * sub_1();
extern  double * sub_1_svc();
#define MUL 3
extern  double * mul_1();
extern  double * mul_1_svc();
#define DIV 4
extern  double * div_1();
extern  double * div_1_svc();
extern int calculatorprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_1_argument (XDR *, add_1_argument*);
extern  bool_t xdr_sub_1_argument (XDR *, sub_1_argument*);
extern  bool_t xdr_mul_1_argument (XDR *, mul_1_argument*);
extern  bool_t xdr_div_1_argument (XDR *, div_1_argument*);

#else /* K&R C */
extern bool_t xdr_add_1_argument ();
extern bool_t xdr_sub_1_argument ();
extern bool_t xdr_mul_1_argument ();
extern bool_t xdr_div_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
