/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculatorprog_1(char *host, int option, float a, float b)
{
	CLIENT *clnt;
	float  *result_calc;
	float num1 = a;
	float num2 = b;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATORPROG, CALCULATORVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (option)
	{
	case 1:
		result_calc = add_1(num1, num2, clnt);
		if (result_calc == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	case 2:
		result_calc = sub_1(num1, num2, clnt);
		if (result_calc == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	case 3:
		result_calc = mul_1(num1, num2, clnt);
		if (result_calc == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	case 4:
		result_calc = div_1(num1, num2, clnt);
		if (result_calc == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	
	default:
		break;
	}

	printf("El resultado es %0.2f\n", *result_calc);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
calculatorvprog_1(char *host)
{
	CLIENT *clnt;
	vect  *result_1;
	vect addv_1_arg1;
	vect addv_1_arg2;
	vect  *result_2;
	vect subv_1_arg1;
	vect subv_1_arg2;
	vect  *result_3;
	vect mulv_1_arg1;
	int mulv_1_arg2;
	matrix  *result_4;
	matrix transpose_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATORVPROG, CALCULATORVVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = addv_1(addv_1_arg1, addv_1_arg2, clnt);
	if (result_1 == (vect *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = subv_1(subv_1_arg1, subv_1_arg2, clnt);
	if (result_2 == (vect *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mulv_1(mulv_1_arg1, mulv_1_arg2, clnt);
	if (result_3 == (vect *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = transpose_1(transpose_1_arg1, clnt);
	if (result_4 == (matrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
palindromechecker_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	word ispalindrome_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, PALINDROMECHECKER, PALINDROMECHECKERVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ispalindrome_1(ispalindrome_1_arg1, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int option;
	float num1, num2;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];

	do
	{
		printf("\nIntroduzca el número de la opción deseada:\n");
		printf("1 - Suma\n2 - Resta\n3 - Multiplicación\n4 - División\n5 - Salir\n");
		scanf("%d", &option);

		switch (option)
		{
		case 1:
			printf("Introduzca los dos sumandos: ");
			scanf("%f %f", &num1, &num2);
			calculatorprog_1 (host, option, num1, num2);
			break;
		case 2:
			printf("Introduzca el minuendo y el sustraendo: ");
			scanf("%f %f", &num1, &num2);
			calculatorprog_1(host, option, num1, num2);
			break;
		case 3:
			printf("Introduzca los dos factores: ");
			scanf("%f %f", &num1, &num2);
			calculatorprog_1(host, option, num1, num2);
			break;
		case 4:
			printf("Introduzca el dividendo y el divisor: ");
			scanf("%f %f", &num1, &num2);

			if (num2 != 0)
				calculatorprog_1(host, option, num1, num2);
			else
				printf("El divisor no puede ser cero\n");
		/*case 5:
			int i = 0;
			int length;
			printf("Introduzca la longitud de los vectores: ");
			scanf("%d", &length);
			vect1.vect_val = malloc(length * sizeof(float));
			vect2.vect_val = malloc(length * sizeof(float));
			printf("Introduzca los %d elementos del primer vector\n", length);
			while(i != length) {
				scanf("%f", &num1);
				vect1.vect_val[i] = num1;
				i++;
			}
			i = 0;
			num1 = 0;
			printf("Introduzca los %d elementos del segundo vector\n", length);
			while(i != length) {
				scanf("%f", &num1);
				vect2.vect_val[i] = num1;
				i++;
			}
			i = 0;
			// DEBUG
			/*
			printf("Num de elementos = %d\n", length);

			printf("Elementos del primer vector: ");
			float a;

			while(i < length) {
				a = vect1.vect_val[i];
				printf("%f ", a);
				i++;
			}

			printf("\n");

			i = 0;

			printf("Elementos del segundo vector: ");

			while(i < length) {
				a = vect2.vect_val[i];
				printf("%f ", a);
				i++;
			}

			printf("\n");
			

			calculatorprog_1(host, option, num1, num2, vect1, vect2, matrix1, word1);

			/*if (num2 != 0)
				calculatorprog_1(host, option, num1, num2, vect1, vect2, matrix1, word1);
			else
				printf("El divisor no puede ser cero\n");*/
			break;

		default:
			printf("Opción no válida, las opciones disponibles son 1, 2, 3, 4 y 5\n");
			break;
		}
	} while (option != 6);
	//calculatorvprog_1 (host);
	//palindromechecker_1 (host);
exit (0);
}
