/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void calculatorprog_1(char *host, int option, double a, double b)
{
	CLIENT *clnt;
	double *result_1;
	double num1 = a;
	double num2 = b;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULATORPROG, CALCULATORVERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	switch (option)
	{
	case 1:
		result_1 = add_1(num1, num2, clnt);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;
	case 2:
		result_1 = sub_1(num1, num2, clnt);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;
	case 3:
		result_1 = mul_1(num1, num2, clnt);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;
	case 4:
		result_1 = div_1(num1, num2, clnt);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	default:
		break;
	}

	printf("El resultado es %0.2f\n", *result_1);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	int option;
	double num1, num2;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	printf("**** Calculadora ****\n");

	do
	{
		printf("\nIntroduzca el número de la opción deseada:\n");
		printf("1 - Suma\n2 - Resta\n3 - Multiplicación\n4 - División\n5 - Salir\n");
		scanf("%d", &option);

		switch (option)
		{
		case 1:
			printf("Introduzca los dos sumandos: ");
			scanf("%lf %lf", &num1, &num2);
			calculatorprog_1(host, 1, num1, num2);
			break;
		case 2:
			printf("Introduzca el minuendo y el sustraendo: ");
			scanf("%lf %lf", &num1, &num2);
			calculatorprog_1(host, 2, num1, num2);
			break;
		case 3:
			printf("Introduzca los dos factores: ");
			scanf("%lf %lf", &num1, &num2);
			calculatorprog_1(host, 3, num1, num2);
			break;
		case 4:
			printf("Introduzca el dividendo y el divisor: ");
			scanf("%lf %lf", &num1, &num2);

			if (num2 != 0)
				calculatorprog_1(host, 4, num1, num2);
			else
				printf("El divisor no puede ser cero\n");
			break;
		case 5:
			break;

		default:
			printf("Opción no válida, las opciones disponibles son 1, 2, 3, 4 y 5\n");
			break;
		}
	} while (option != 5);

	exit(0);
}
