/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
add_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 + arg2;

	return &result;
}

float *
sub_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 - arg2;

	return &result;
}

float *
mul_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 * arg2;

	return &result;
}

float *
div_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 / arg2;

	return &result;
}

vect *
addv_1_svc(vect arg1, vect arg2,  struct svc_req *rqstp)
{
	static vect  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vect *
subv_1_svc(vect arg1, vect arg2,  struct svc_req *rqstp)
{
	static vect  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vect *
mulv_1_svc(vect arg1, int arg2,  struct svc_req *rqstp)
{
	static vect  result;

	/*
	 * insert server code here
	 */

	return &result;
}

matrix *
transpose_1_svc(matrix arg1,  struct svc_req *rqstp)
{
	static matrix  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ispalindrome_1_svc(word arg1,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
